apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtsp-simple-server.fullname" . }}
  labels:
    {{- include "rtsp-simple-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.rtsp.port }}
      targetPort: rtsp
      protocol: TCP
      name: rtsp
    - port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.gstreamer.port }}
      targetPort: gstreamer
      protocol: UDP
      name: gstreamer
    - port: {{ .Values.service.api.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "rtsp-simple-server.selectorLabels" . | nindent 4 }}
