
name: build container image (rtsp simple server, ubuntu 20.04 and gstreamer) and push

on:
  push:
    paths:
      - 'Dockerfile'

jobs:
  docker-gstreamer:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: sordfish/rtsp-simple-server-ubuntu-gstreamer:latest,sordfish/rtsp-simple-server-ubuntu-gstreamer:v0.19.3